// Generated by the protocol buffer compiler.  DO NOT EDIT!

package lz.com.tools.nano;

@SuppressWarnings("hiding")
public final class AddressBook extends
    com.google.protobuf.nano.android.ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final android.os.Parcelable.Creator<AddressBook> CREATOR =
      new com.google.protobuf.nano.android.ParcelableMessageNanoCreator<
          AddressBook>(AddressBook.class);

  private static volatile AddressBook[] _emptyArray;
  public static AddressBook[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new AddressBook[0];
        }
      }
    }
    return _emptyArray;
  }

  // repeated .lz.com.tools.Person person = 1;
  public lz.com.tools.nano.Person[] person;

  public AddressBook() {
    clear();
  }

  public AddressBook clear() {
    person = lz.com.tools.nano.Person.emptyArray();
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.person != null && this.person.length > 0) {
      for (int i = 0; i < this.person.length; i++) {
        lz.com.tools.nano.Person element = this.person[i];
        if (element != null) {
          output.writeMessage(1, element);
        }
      }
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.person != null && this.person.length > 0) {
      for (int i = 0; i < this.person.length; i++) {
        lz.com.tools.nano.Person element = this.person[i];
        if (element != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, element);
        }
      }
    }
    return size;
  }

  @Override
  public AddressBook mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          int arrayLength = com.google.protobuf.nano.WireFormatNano
              .getRepeatedFieldArrayLength(input, 10);
          int i = this.person == null ? 0 : this.person.length;
          lz.com.tools.nano.Person[] newArray =
              new lz.com.tools.nano.Person[i + arrayLength];
          if (i != 0) {
            java.lang.System.arraycopy(this.person, 0, newArray, 0, i);
          }
          for (; i < newArray.length - 1; i++) {
            newArray[i] = new lz.com.tools.nano.Person();
            input.readMessage(newArray[i]);
            input.readTag();
          }
          // Last one without readTag.
          newArray[i] = new lz.com.tools.nano.Person();
          input.readMessage(newArray[i]);
          this.person = newArray;
          break;
        }
      }
    }
  }

  public static AddressBook parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new AddressBook(), data);
  }

  public static AddressBook parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new AddressBook().mergeFrom(input);
  }
}
