// Generated by the protocol buffer compiler.  DO NOT EDIT!

package lz.com.tools.nano;

@SuppressWarnings("hiding")
public final class ZRequest extends
    com.google.protobuf.nano.android.ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final android.os.Parcelable.Creator<ZRequest> CREATOR =
      new com.google.protobuf.nano.android.ParcelableMessageNanoCreator<
          ZRequest>(ZRequest.class);

  private static volatile ZRequest[] _emptyArray;
  public static ZRequest[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new ZRequest[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional bytes ZPack = 1;
  public byte[] zPack;

  // optional string MethodName = 2;
  public java.lang.String methodName;

  public ZRequest() {
    clear();
  }

  public ZRequest clear() {
    zPack = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    methodName = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!java.util.Arrays.equals(this.zPack, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(1, this.zPack);
    }
    if (!this.methodName.equals("")) {
      output.writeString(2, this.methodName);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!java.util.Arrays.equals(this.zPack, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(1, this.zPack);
    }
    if (!this.methodName.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.methodName);
    }
    return size;
  }

  @Override
  public ZRequest mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.zPack = input.readBytes();
          break;
        }
        case 18: {
          this.methodName = input.readString();
          break;
        }
      }
    }
  }

  public static ZRequest parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new ZRequest(), data);
  }

  public static ZRequest parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new ZRequest().mergeFrom(input);
  }
}
